//! Generate fetcher / renderer reference Markdown from the live registries.
//!
//! Layout:
//! - `<out>/matrix.md` — overview: fetcher index, renderer index, shape×renderer matrix.
//! - `<out>/fetchers/<family>/<name>.md` — every fetcher page lives inside its family
//!   subdir (family = the segment before the first underscore). `clock_ratio` joins
//!   `clock/`, `github_my_prs` joins `github/`, and Starlight's `autogenerate` surfaces
//!   each family as a collapsible sidebar group. Same split for renderers. The project
//!   keeps the family prefix on every registered name (see
//!   [`AGENTS.md`](../../../AGENTS.md) — "Family prefix for every named token"), so
//!   there are no orphans to worry about.
//!
//! The whole point is that these pages can't drift from code: anyone adding a fetcher or
//! renderer re-runs `cargo xtask gen-matrix` and the catalog updates mechanically.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use std::sync::Arc;

use anyhow::{Context, Result};
use splashboard::fetcher::{RegisteredFetcher, Registry as FetcherRegistry, Safety};
use splashboard::options::OptionSchema;
use splashboard::render::{Registry as RenderRegistry, Renderer, Shape};
use splashboard::theme::ColorKey;

use crate::snapshots;

const ALL_SHAPES: &[Shape] = &[
    Shape::Text,
    Shape::TextBlock,
    Shape::Entries,
    Shape::Ratio,
    Shape::NumberSeries,
    Shape::PointSeries,
    Shape::Bars,
    Shape::Image,
    Shape::Calendar,
    Shape::Heatmap,
    Shape::Badge,
    Shape::Timeline,
];

pub fn run(out: &Path) -> Result<()> {
    let fetchers = FetcherRegistry::with_builtins();
    let renderers = RenderRegistry::with_builtins();
    write_file(&out.join("matrix.md"), &overview(&fetchers, &renderers))?;
    for f in fetchers.sorted() {
        let page = fetcher_page(&f, &renderers);
        write_file(&out.join(rel_path("fetchers", f.name())), &page)?;
    }
    for r in renderers.sorted() {
        let page = renderer_page(&r, &fetchers, &renderers);
        write_file(&out.join(rel_path("renderers", r.name())), &page)?;
    }
    Ok(())
}

/// Path for one catalog entry inside the reference tree. Every name carries a family prefix
/// by project convention, so grouping is unconditional: `clock_ratio` → `clock/clock_ratio.md`,
/// `media_image` → `media/media_image.md`.
fn rel_path(kind: &str, name: &str) -> String {
    format!("{kind}/{}/{name}.md", family_of(name))
}

/// Cross-link between two pages. Both live at depth 2 under the reference root
/// (`<kind>/<family>/<name>.md`), so every hop is `../../<kind>/<family>/<name>.md`.
fn cross_link(to_kind: &str, to_name: &str) -> String {
    format!("../../{}/{}/{to_name}.md", to_kind, family_of(to_name))
}

fn family_of(name: &str) -> &str {
    name.split_once('_').map(|(f, _)| f).unwrap_or(name)
}

fn write_file(path: &Path, body: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("create parent dir for {}", path.display()))?;
    }
    fs::write(path, body).with_context(|| format!("write {}", path.display()))?;
    println!("wrote {}", path.display());
    Ok(())
}

fn overview(fetchers: &FetcherRegistry, renderers: &RenderRegistry) -> String {
    let mut out = String::new();
    push_frontmatter(
        &mut out,
        "Reference",
        "Fetcher index, renderer index, and the shape × renderer compatibility matrix.",
    );
    out.push_str(
        "Generated by `cargo xtask` from the built-in registries. Do not edit by hand.\n\n",
    );
    overview_fetcher_table(&mut out, fetchers);
    overview_renderer_table(&mut out, renderers);
    overview_shape_matrix(&mut out, renderers);
    out
}

fn overview_fetcher_table(out: &mut String, fetchers: &FetcherRegistry) {
    out.push_str("## Fetchers\n\n");
    out.push_str("| Name | Kind | Safety | Shapes | Description |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for f in fetchers.sorted() {
        let _ = writeln!(
            out,
            "| [`{name}`]({link}) | {kind} | {safety} | {shapes} | {description} |",
            name = f.name(),
            link = rel_path("fetchers", f.name()),
            kind = kind_label(&f),
            safety = safety_label(f.safety()),
            shapes = shapes_list(&f.shapes()),
            description = escape_pipe(f.description()),
        );
    }
    out.push('\n');
}

fn overview_renderer_table(out: &mut String, renderers: &RenderRegistry) {
    out.push_str("## Renderers\n\n");
    out.push_str("| Name | Accepts | Animates | Description |\n");
    out.push_str("| --- | --- | --- | --- |\n");
    for r in renderers.sorted() {
        let _ = writeln!(
            out,
            "| [`{name}`]({link}) | {accepts} | {animates} | {description} |",
            name = r.name(),
            link = rel_path("renderers", r.name()),
            accepts = shapes_list(r.accepts()),
            animates = if r.animates() { "yes" } else { "no" },
            description = escape_pipe(r.description()),
        );
    }
    out.push('\n');
}

fn overview_shape_matrix(out: &mut String, renderers: &RenderRegistry) {
    out.push_str("## Shape × Renderer\n\n");
    let sorted = renderers.sorted();
    out.push_str("| Shape \\ Renderer |");
    for r in &sorted {
        let _ = write!(out, " `{}` |", r.name());
    }
    out.push('\n');
    out.push('|');
    for _ in 0..=sorted.len() {
        out.push_str(" --- |");
    }
    out.push('\n');
    for shape in ALL_SHAPES {
        let _ = write!(out, "| `{}` |", shape.as_str());
        for r in &sorted {
            let cell = if r.accepts().contains(shape) {
                "✓"
            } else {
                ""
            };
            let _ = write!(out, " {cell} |");
        }
        out.push('\n');
    }
    out.push('\n');
}

fn fetcher_page(f: &RegisteredFetcher, renderers: &RenderRegistry) -> String {
    let mut out = String::new();
    push_frontmatter(&mut out, f.name(), f.description());
    let _ = writeln!(out, "{}\n", f.description());
    out.push_str("| Kind | Safety | Shapes |\n");
    out.push_str("| --- | --- | --- |\n");
    let _ = writeln!(
        out,
        "| {kind} | {safety} | {shapes} |\n",
        kind = kind_label(f),
        safety = safety_label(f.safety()),
        shapes = shapes_list(&f.shapes()),
    );
    render_option_section(
        &mut out,
        f.option_schemas(),
        "Options",
        option_fallback_fetcher(),
    );
    render_compatible_renderers(&mut out, &f.shapes(), renderers);
    render_previews(&mut out, f, renderers);
    out
}

fn render_previews(out: &mut String, fetcher: &RegisteredFetcher, renderers: &RenderRegistry) {
    let previews = snapshots::previews_for(fetcher, renderers);
    render_preview_section(out, previews, |p| {
        format!("`{}` via `{}`", p.shape.as_str(), p.renderer)
    });
}

fn render_renderer_previews(
    out: &mut String,
    renderer: &Arc<dyn Renderer>,
    fetchers: &FetcherRegistry,
    renderers: &RenderRegistry,
) {
    let previews = snapshots::previews_for_renderer(renderer, fetchers, renderers);
    render_preview_section(out, previews, |p| format!("`{}`", p.shape.as_str()));
}

fn render_preview_section<F>(out: &mut String, previews: Vec<snapshots::Preview>, heading: F)
where
    F: Fn(&snapshots::Preview) -> String,
{
    if previews.is_empty() {
        return;
    }
    out.push_str("## Preview\n\n");
    for p in previews {
        let _ = writeln!(out, "### {}\n", heading(&p));
        out.push_str(&p.html);
        out.push_str("\n\n");
        out.push_str("```toml\n");
        out.push_str(&p.config_snippet);
        out.push_str("\n```\n\n");
    }
}

fn renderer_page(
    r: &Arc<dyn Renderer>,
    fetchers: &FetcherRegistry,
    renderers: &RenderRegistry,
) -> String {
    let mut out = String::new();
    push_frontmatter(&mut out, r.name(), r.description());
    let _ = writeln!(out, "{}\n", r.description());
    out.push_str("| Accepts | Animates |\n");
    out.push_str("| --- | --- |\n");
    let _ = writeln!(
        out,
        "| {accepts} | {animates} |\n",
        accepts = shapes_list(r.accepts()),
        animates = if r.animates() { "yes" } else { "no" },
    );
    render_option_section(
        &mut out,
        r.option_schemas(),
        "Options",
        option_fallback_renderer(),
    );
    render_color_keys_section(&mut out, r.color_keys());
    render_compatible_fetchers(&mut out, r.accepts(), fetchers);
    render_renderer_previews(&mut out, r, fetchers, renderers);
    out
}

fn render_color_keys_section(out: &mut String, keys: &[ColorKey]) {
    out.push_str("## Theme tokens\n\n");
    if keys.is_empty() {
        out.push_str("_This renderer does not read any `[theme]` tokens._\n\n");
        return;
    }
    out.push_str("Overridable via the `[theme]` section of `config.toml`.\n\n");
    out.push_str("| Key | Description |\n");
    out.push_str("| --- | --- |\n");
    for k in keys {
        let _ = writeln!(
            out,
            "| `{name}` | {desc} |",
            name = k.name,
            desc = escape_pipe(k.description),
        );
    }
    out.push('\n');
}

/// Starlight uses `title` from frontmatter; authoring an H1 in the body would duplicate.
fn push_frontmatter(out: &mut String, title: &str, description: &str) {
    out.push_str("---\n");
    let _ = writeln!(out, "title: {}", yaml_string(title));
    let _ = writeln!(out, "description: {}", yaml_string(description));
    out.push_str("---\n\n");
}

/// YAML scalar that survives colons, backticks, and the other metacharacters we actually
/// generate. Double-quoted with backslash escapes is the lowest-footgun choice.
fn yaml_string(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

fn render_option_section(
    out: &mut String,
    schemas: &[OptionSchema],
    heading: &str,
    fallback: &str,
) {
    let _ = writeln!(out, "## {heading}\n");
    if schemas.is_empty() {
        let _ = writeln!(out, "{fallback}\n");
        return;
    }
    out.push_str("| Option | Type | Required | Default | Description |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for s in schemas {
        let required = if s.required { "yes" } else { "no" };
        let default = s.default.unwrap_or("—");
        let _ = writeln!(
            out,
            "| `{name}` | {ty} | {required} | {default} | {desc} |",
            name = s.name,
            ty = escape_pipe(s.type_hint),
            default = escape_pipe(default),
            desc = escape_pipe(s.description),
        );
    }
    out.push('\n');
}

fn option_fallback_fetcher() -> &'static str {
    "_No options._"
}

fn option_fallback_renderer() -> &'static str {
    "_No options beyond the shared `RenderOptions` defaults._"
}

fn render_compatible_renderers(out: &mut String, shapes: &[Shape], renderers: &RenderRegistry) {
    out.push_str("## Compatible renderers\n\n");
    out.push_str("| Shape | Renderers |\n");
    out.push_str("| --- | --- |\n");
    let sorted = renderers.sorted();
    for shape in shapes {
        let matches: Vec<String> = sorted
            .iter()
            .filter(|r| r.accepts().contains(shape))
            .map(|r| {
                format!(
                    "[`{name}`]({link})",
                    name = r.name(),
                    link = cross_link("renderers", r.name()),
                )
            })
            .collect();
        let cell = if matches.is_empty() {
            "_none_".into()
        } else {
            matches.join(", ")
        };
        let _ = writeln!(out, "| `{}` | {} |", shape.as_str(), cell);
    }
    out.push('\n');
}

fn render_compatible_fetchers(out: &mut String, shapes: &[Shape], fetchers: &FetcherRegistry) {
    out.push_str("## Compatible fetchers\n\n");
    out.push_str("| Shape | Fetchers |\n");
    out.push_str("| --- | --- |\n");
    let sorted = fetchers.sorted();
    for shape in shapes {
        let matches: Vec<String> = sorted
            .iter()
            .filter(|f| f.shapes().contains(shape))
            .map(|f| {
                format!(
                    "[`{name}`]({link})",
                    name = f.name(),
                    link = cross_link("fetchers", f.name()),
                )
            })
            .collect();
        let cell = if matches.is_empty() {
            "_none_".into()
        } else {
            matches.join(", ")
        };
        let _ = writeln!(out, "| `{}` | {} |", shape.as_str(), cell);
    }
    out.push('\n');
}

fn kind_label(f: &RegisteredFetcher) -> &'static str {
    match f {
        RegisteredFetcher::Cached(_) => "cached",
        RegisteredFetcher::Realtime(_) => "realtime",
    }
}

fn safety_label(s: Safety) -> &'static str {
    match s {
        Safety::Safe => "Safe",
        Safety::Network => "Network",
        Safety::Exec => "Exec",
    }
}

fn shapes_list(shapes: &[Shape]) -> String {
    shapes
        .iter()
        .map(|s| format!("`{}`", s.as_str()))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Escape pipe characters inside Markdown table cells. Without this, a type hint like
/// `"\"full\" | \"quadrant\""` breaks the row.
fn escape_pipe(s: &str) -> String {
    s.replace('|', "\\|")
}
