//! Generate fetcher / renderer reference Markdown from the live registries.
//!
//! Layout:
//! - `<out>/matrix.md` — overview: fetcher index, renderer index, shape×renderer matrix.
//! - `<out>/fetchers/<family>/<name>.md` — every fetcher page lives inside its family
//!   subdir (family = the segment before the first underscore). `clock_ratio` joins
//!   `clock/`, `github_my_prs` joins `github/`, and Starlight's `autogenerate` surfaces
//!   each family as a collapsible sidebar group. Same split for renderers. The project
//!   keeps the family prefix on every registered name (see
//!   [`AGENTS.md`](../../../AGENTS.md) — "Family prefix for every named token"), so
//!   there are no orphans to worry about.
//!
//! The whole point is that these pages can't drift from code: anyone adding a fetcher or
//! renderer re-runs `cargo xtask gen-matrix` and the catalog updates mechanically.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use std::sync::Arc;

use anyhow::{Context, Result};
use splashboard::fetcher::{RegisteredFetcher, Registry as FetcherRegistry, Safety};
use splashboard::options::OptionSchema;
use splashboard::render::{Registry as RenderRegistry, Renderer, Shape};
use splashboard::theme::ColorKey;

use crate::snapshots;

const ALL_SHAPES: &[Shape] = &[
    Shape::Text,
    Shape::TextBlock,
    Shape::Entries,
    Shape::Ratio,
    Shape::NumberSeries,
    Shape::PointSeries,
    Shape::Bars,
    Shape::Image,
    Shape::Calendar,
    Shape::Heatmap,
    Shape::Badge,
    Shape::Timeline,
];

pub fn run(out: &Path) -> Result<()> {
    let fetchers = FetcherRegistry::with_builtins();
    let renderers = RenderRegistry::with_builtins();
    write_file(&out.join("matrix.md"), &overview(&fetchers, &renderers))?;
    for f in fetchers.sorted() {
        let page = fetcher_page(&f, &renderers);
        write_file(&out.join(rel_path("fetchers", f.name())), &page)?;
    }
    for r in renderers.sorted() {
        let page = renderer_page(&r, &fetchers, &renderers);
        write_file(&out.join(rel_path("renderers", r.name())), &page)?;
    }
    Ok(())
}

/// Path for one catalog entry inside the reference tree. Every name carries a family prefix
/// by project convention, so grouping is unconditional: `clock_ratio` → `clock/clock_ratio.md`,
/// `media_image` → `media/media_image.md`.
fn rel_path(kind: &str, name: &str) -> String {
    format!("{kind}/{}/{name}.md", family_of(name))
}

/// Same-level link from `matrix.md` (the reference root) to a page. Targets the rendered
/// route, not the source file: `copy-markdown.mjs` mirrors every `.md` into `dist/`, so a
/// `.md` href would land on the raw source instead of the Starlight-rendered page.
fn rel_link(kind: &str, name: &str) -> String {
    format!("{kind}/{}/{name}/", family_of(name))
}

/// Cross-link between two pages. Both live at depth 2 under the reference root, so every
/// hop is `../../<kind>/<family>/<name>/`. Trailing slash, no `.md`: same reason as
/// `rel_link` — point at the route, not the mirrored source.
fn cross_link(to_kind: &str, to_name: &str) -> String {
    format!("../../{}/{}/{to_name}/", to_kind, family_of(to_name))
}

fn family_of(name: &str) -> &str {
    name.split_once('_').map(|(f, _)| f).unwrap_or(name)
}

fn write_file(path: &Path, body: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("create parent dir for {}", path.display()))?;
    }
    fs::write(path, body).with_context(|| format!("write {}", path.display()))?;
    println!("wrote {}", path.display());
    Ok(())
}

fn overview(fetchers: &FetcherRegistry, renderers: &RenderRegistry) -> String {
    let mut out = String::new();
    push_frontmatter(
        &mut out,
        "Reference",
        "Fetcher index, renderer index, and the shape × renderer compatibility matrix.",
    );
    out.push_str(
        "Generated by `cargo xtask` from the built-in registries. Do not edit by hand.\n\n",
    );
    overview_fetcher_table(&mut out, fetchers);
    overview_renderer_table(&mut out, renderers);
    overview_shape_matrix(&mut out, renderers);
    out
}

fn overview_fetcher_table(out: &mut String, fetchers: &FetcherRegistry) {
    out.push_str("## Fetchers\n\n");
    out.push_str("| Name | Kind | Safety | Shapes | Description |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for f in fetchers.sorted() {
        let _ = writeln!(
            out,
            "| [`{name}`]({link}) | {kind} | {safety} | {shapes} | {description} |",
            name = f.name(),
            link = rel_link("fetchers", f.name()),
            kind = kind_label(&f),
            safety = safety_label(f.safety()),
            shapes = shapes_list(&f.shapes()),
            description = escape_pipe(f.description()),
        );
    }
    out.push('\n');
}

fn overview_renderer_table(out: &mut String, renderers: &RenderRegistry) {
    out.push_str("## Renderers\n\n");
    out.push_str("| Name | Accepts | Animates | Description |\n");
    out.push_str("| --- | --- | --- | --- |\n");
    for r in renderers.sorted() {
        let _ = writeln!(
            out,
            "| [`{name}`]({link}) | {accepts} | {animates} | {description} |",
            name = r.name(),
            link = rel_link("renderers", r.name()),
            accepts = shapes_list(r.accepts()),
            animates = if r.animates() { "yes" } else { "no" },
            description = escape_pipe(r.description()),
        );
    }
    out.push('\n');
}

fn overview_shape_matrix(out: &mut String, renderers: &RenderRegistry) {
    out.push_str("## Shape × Renderer\n\n");
    let sorted = renderers.sorted();
    out.push_str("| Shape \\ Renderer |");
    for r in &sorted {
        let _ = write!(out, " `{}` |", r.name());
    }
    out.push('\n');
    out.push('|');
    for _ in 0..=sorted.len() {
        out.push_str(" --- |");
    }
    out.push('\n');
    for shape in ALL_SHAPES {
        let _ = write!(out, "| `{}` |", shape.as_str());
        for r in &sorted {
            let cell = if r.accepts().contains(shape) {
                "✓"
            } else {
                ""
            };
            let _ = write!(out, " {cell} |");
        }
        out.push('\n');
    }
    out.push('\n');
}

fn fetcher_page(f: &RegisteredFetcher, renderers: &RenderRegistry) -> String {
    let mut out = String::new();
    push_frontmatter(&mut out, f.name(), f.description());
    let _ = writeln!(out, "{}\n", f.description());
    out.push_str("| Kind | Safety | Shapes |\n");
    out.push_str("| --- | --- | --- |\n");
    let _ = writeln!(
        out,
        "| {kind} | {safety} | {shapes} |\n",
        kind = kind_label(f),
        safety = safety_label(f.safety()),
        shapes = shapes_list(&f.shapes()),
    );
    render_option_section(
        &mut out,
        f.option_schemas(),
        "Options",
        option_fallback_fetcher(),
    );
    render_compatible_renderers(&mut out, &f.shapes(), renderers);
    render_previews(&mut out, f, renderers);
    out
}

fn render_previews(out: &mut String, fetcher: &RegisteredFetcher, renderers: &RenderRegistry) {
    let previews = snapshots::previews_for(fetcher, renderers);
    render_preview_section(out, previews, |p| {
        format!("`{}` via `{}`", p.shape.as_str(), p.renderer)
    });
}

fn render_renderer_previews(
    out: &mut String,
    renderer: &Arc<dyn Renderer>,
    fetchers: &FetcherRegistry,
    renderers: &RenderRegistry,
) {
    let previews = snapshots::previews_for_renderer(renderer, fetchers, renderers);
    render_preview_section(out, previews, |p| format!("`{}`", p.shape.as_str()));
}

fn render_preview_section<F>(out: &mut String, previews: Vec<snapshots::Preview>, heading: F)
where
    F: Fn(&snapshots::Preview) -> String,
{
    if previews.is_empty() {
        return;
    }
    out.push_str("## Preview\n\n");
    for p in previews {
        let _ = writeln!(out, "### {}\n", heading(&p));
        out.push_str(&p.html);
        out.push_str("\n\n");
        out.push_str("```toml\n");
        out.push_str(&p.config_snippet);
        out.push_str("\n```\n\n");
    }
}

fn renderer_page(
    r: &Arc<dyn Renderer>,
    fetchers: &FetcherRegistry,
    renderers: &RenderRegistry,
) -> String {
    let mut out = String::new();
    push_frontmatter(&mut out, r.name(), r.description());
    let _ = writeln!(out, "{}\n", r.description());
    out.push_str("| Accepts | Animates |\n");
    out.push_str("| --- | --- |\n");
    let _ = writeln!(
        out,
        "| {accepts} | {animates} |\n",
        accepts = shapes_list(r.accepts()),
        animates = if r.animates() { "yes" } else { "no" },
    );
    render_option_section(
        &mut out,
        r.option_schemas(),
        "Options",
        option_fallback_renderer(),
    );
    render_color_keys_section(&mut out, r.color_keys());
    render_compatible_fetchers(&mut out, r.accepts(), fetchers);
    render_renderer_previews(&mut out, r, fetchers, renderers);
    out
}

fn render_color_keys_section(out: &mut String, keys: &[ColorKey]) {
    out.push_str("## Theme tokens\n\n");
    if keys.is_empty() {
        out.push_str("_This renderer does not read any `[theme]` tokens._\n\n");
        return;
    }
    out.push_str("Overridable via the `[theme]` section of `config.toml`.\n\n");
    out.push_str("| Key | Description |\n");
    out.push_str("| --- | --- |\n");
    for k in keys {
        let _ = writeln!(
            out,
            "| `{name}` | {desc} |",
            name = k.name,
            desc = escape_pipe(k.description),
        );
    }
    out.push('\n');
}

/// Starlight uses `title` from frontmatter; authoring an H1 in the body would duplicate.
fn push_frontmatter(out: &mut String, title: &str, description: &str) {
    out.push_str("---\n");
    let _ = writeln!(out, "title: {}", yaml_string(title));
    let _ = writeln!(out, "description: {}", yaml_string(description));
    out.push_str("---\n\n");
}

/// YAML scalar that survives colons, backticks, and the other metacharacters we actually
/// generate. Double-quoted with backslash escapes is the lowest-footgun choice.
fn yaml_string(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

fn render_option_section(
    out: &mut String,
    schemas: &[OptionSchema],
    heading: &str,
    fallback: &str,
) {
    let _ = writeln!(out, "## {heading}\n");
    if schemas.is_empty() {
        let _ = writeln!(out, "{fallback}\n");
        return;
    }
    out.push_str("| Option | Type | Required | Default | Description |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for s in schemas {
        let required = if s.required { "yes" } else { "no" };
        let default = s.default.unwrap_or("—");
        let _ = writeln!(
            out,
            "| `{name}` | {ty} | {required} | {default} | {desc} |",
            name = s.name,
            ty = escape_pipe(s.type_hint),
            default = escape_pipe(default),
            desc = escape_pipe(s.description),
        );
    }
    out.push('\n');
}

fn option_fallback_fetcher() -> &'static str {
    "_No options._"
}

fn option_fallback_renderer() -> &'static str {
    "_No options beyond the shared `RenderOptions` defaults._"
}

fn render_compatible_renderers(out: &mut String, shapes: &[Shape], renderers: &RenderRegistry) {
    out.push_str("## Compatible renderers\n\n");
    out.push_str("| Shape | Renderers |\n");
    out.push_str("| --- | --- |\n");
    let sorted = renderers.sorted();
    for shape in shapes {
        let matches: Vec<String> = sorted
            .iter()
            .filter(|r| r.accepts().contains(shape))
            .map(|r| {
                format!(
                    "[`{name}`]({link})",
                    name = r.name(),
                    link = cross_link("renderers", r.name()),
                )
            })
            .collect();
        let cell = if matches.is_empty() {
            "_none_".into()
        } else {
            matches.join(", ")
        };
        let _ = writeln!(out, "| `{}` | {} |", shape.as_str(), cell);
    }
    out.push('\n');
}

fn render_compatible_fetchers(out: &mut String, shapes: &[Shape], fetchers: &FetcherRegistry) {
    out.push_str("## Compatible fetchers\n\n");
    out.push_str("| Shape | Fetchers |\n");
    out.push_str("| --- | --- |\n");
    let sorted = fetchers.sorted();
    for shape in shapes {
        let matches: Vec<String> = sorted
            .iter()
            .filter(|f| f.shapes().contains(shape))
            .map(|f| {
                format!(
                    "[`{name}`]({link})",
                    name = f.name(),
                    link = cross_link("fetchers", f.name()),
                )
            })
            .collect();
        let cell = if matches.is_empty() {
            "_none_".into()
        } else {
            matches.join(", ")
        };
        let _ = writeln!(out, "| `{}` | {} |", shape.as_str(), cell);
    }
    out.push('\n');
}

fn kind_label(f: &RegisteredFetcher) -> &'static str {
    match f {
        RegisteredFetcher::Cached(_) => "cached",
        RegisteredFetcher::Realtime(_) => "realtime",
    }
}

fn safety_label(s: Safety) -> &'static str {
    match s {
        Safety::Safe => "Safe",
        Safety::Network => "Network",
        Safety::Exec => "Exec",
    }
}

fn shapes_list(shapes: &[Shape]) -> String {
    shapes
        .iter()
        .map(|s| format!("`{}`", s.as_str()))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Escape pipe characters inside Markdown table cells. Without this, a type hint like
/// `"\"full\" | \"quadrant\""` breaks the row.
fn escape_pipe(s: &str) -> String {
    s.replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::*;
    use splashboard::theme::TEXT;

    #[test]
    fn run_writes_reference_tree_with_grouped_pages() {
        let out_dir = unique_out_dir();

        run(&out_dir).expect("gen-matrix should render the reference tree");

        let overview = read(&out_dir.join("matrix.md"));
        assert!(overview.contains("## Fetchers"));
        assert!(overview.contains("## Renderers"));
        assert!(overview.contains("## Shape × Renderer"));
        assert!(overview.contains("[`clock`](fetchers/clock/clock/)"));
        assert!(overview.contains("[`text_plain`](renderers/text/text_plain/)"));

        let fetcher_page = read(&out_dir.join("fetchers/clock/clock.md"));
        assert!(fetcher_page.contains("## Compatible renderers"));
        assert!(fetcher_page.contains("## Preview"));
        assert!(fetcher_page.contains("../../renderers/text/text_plain/"));

        let renderer_page = read(&out_dir.join("renderers/text/text_plain.md"));
        assert!(renderer_page.contains("## Compatible fetchers"));
        assert!(renderer_page.contains("## Theme tokens"));
        assert!(renderer_page.contains("../../fetchers/clock/clock/"));

        fs::remove_dir_all(out_dir).expect("temp output dir should be removable");
    }

    #[test]
    fn compatible_sections_render_none_for_error_shape() {
        let fetchers = FetcherRegistry::with_builtins();
        let renderers = RenderRegistry::with_builtins();

        let mut renderer_out = String::new();
        render_compatible_renderers(&mut renderer_out, &[Shape::Error], &renderers);
        assert!(renderer_out.contains("| `error` | _none_ |"));

        let mut fetcher_out = String::new();
        render_compatible_fetchers(&mut fetcher_out, &[Shape::Error], &fetchers);
        assert!(fetcher_out.contains("| `error` | _none_ |"));
    }

    #[test]
    fn helpers_escape_special_chars_and_emit_fallbacks() {
        let mut frontmatter = String::new();
        push_frontmatter(
            &mut frontmatter,
            r#"Title: "quoted"\path"#,
            "desc with `code`",
        );
        assert!(frontmatter.contains(r#"title: "Title: \"quoted\"\\path""#));
        assert!(frontmatter.contains(r#"description: "desc with `code`""#));

        let mut options = String::new();
        render_option_section(&mut options, &[], "Options", option_fallback_fetcher());
        assert!(options.contains("_No options._"));

        let mut option_table = String::new();
        render_option_section(
            &mut option_table,
            &[OptionSchema {
                name: "mode",
                type_hint: "\"full\" | \"compact\"",
                required: false,
                default: Some("\"full\""),
                description: "Pipe | survives markdown tables.",
            }],
            "Options",
            option_fallback_renderer(),
        );
        assert!(option_table.contains("\\|"));

        let mut colors = String::new();
        render_color_keys_section(&mut colors, &[]);
        assert!(colors.contains("does not read any `[theme]` tokens"));

        let mut color_table = String::new();
        render_color_keys_section(&mut color_table, &[TEXT]);
        assert!(color_table.contains("| `text` |"));

        assert_eq!(
            rel_path("renderers", "text_plain"),
            "renderers/text/text_plain.md"
        );
        assert_eq!(
            rel_link("fetchers", "clock_ratio"),
            "fetchers/clock/clock_ratio/"
        );
        assert_eq!(
            cross_link("renderers", "text_plain"),
            "../../renderers/text/text_plain/"
        );
        assert_eq!(family_of("clock"), "clock");
        assert_eq!(family_of("clock_ratio"), "clock");
        assert_eq!(safety_label(Safety::Exec), "Exec");
        assert_eq!(
            shapes_list(&[Shape::Text, Shape::Timeline]),
            "`text`, `timeline`"
        );
        assert_eq!(escape_pipe("left|right"), "left\\|right");
    }

    fn read(path: &Path) -> String {
        fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
    }

    fn unique_out_dir() -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock should be after unix epoch")
            .as_nanos();
        std::env::temp_dir().join(format!(
            "splashboard-gen-matrix-{}-{nanos}",
            std::process::id()
        ))
    }
}
